# Generated by Django 4.1.7 on 2023-04-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
    ]
